config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :mortgages, only: %i[index show new create] do
    resource :equity_tracker, only: %i[new create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Base model class for the application
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equity_tracker.rb
# frozen_string_literal: true

# Represents information needed to track mortgage equity in YNAB
class EquityTracker < ApplicationRecord
  belongs_to :mortgage
end

app/models/equity_tracker_form.rb
# frozen_string_literal: true

# Represents a mortgage equity tracker in terms of attributes for a form
class EquityTrackerForm
  include ActiveModel::Model

  attr_accessor :account_id
  attr_accessor :budget_id
  attr_accessor :payee_name
  attr_accessor :step

  with_options if: :past_step_1? do
    validates :budget_id, presence: true
  end
  with_options if: :past_step_2? do
    validates :account_id, presence: true
    validates :payee_name, presence: true
  end

  def initialize(*args)
    super(*args)
    coerce_step
  end

  def completed?
    valid? && step == 3
  end

  def past_step_1?
    step.present? && step > 1
  end

  def past_step_2?
    step.present? && step > 2
  end

  private

  def coerce_step
    self.step = if %w[1 2 3].include?(step)
                  step.to_i
                else
                  1
                end
  end
end

app/models/mortgage.rb
# frozen_string_literal: true

# Represents a user's mortgage
class Mortgage < ApplicationRecord
  belongs_to :user

  has_one :equity_tracker, dependent: :destroy

  def amortization_schedule
    balance = amount
    equity = start_equity
    payment = monthly_payment
    periodic_rate = monthly_interest_rate

    schedule = Array.new(number_of_payments) do |index|
      interest = MilliMoney.from_money(balance * periodic_rate)
      principal = MilliMoney.from_money(payment - interest)
      balance = MilliMoney.from_money(balance - principal)
      equity = MilliMoney.from_money(equity + principal)

      OpenStruct.new(
        balance: balance,
        date: start_date.advance(months: index),
        equity: equity,
        interest: interest,
        number: index + 1,
        principal: principal
      )
    end

    penultimate_period, last_period = schedule.last(2)
    last_period.balance = MilliMoney.new(currency: currency, milliunits: 0)
    last_period.equity = MilliMoney.from_money(amount + start_equity)
    last_period.principal = penultimate_period.balance
    last_period.interest = MilliMoney.from_money(payment - last_period.principal)

    schedule
  end

  def amount
    MilliMoney.new(currency: currency, milliunits: amount_milliunits)
  end

  def monthly_payment
    MilliMoney.new(currency: currency, milliunits: monthly_payment_milliunits)
  end

  def start_equity
    MilliMoney.new(currency: currency, milliunits: start_equity_milliunits)
  end

  def total_cost
    MilliMoney.from_money(monthly_payment * number_of_payments)
  end

  private

  def monthly_interest_rate
    interest_rate / 12
  end

  def monthly_payment_milliunits
    a = amount_milliunits
    n = number_of_payments
    r = monthly_interest_rate

    ((r * a) / (1 - (1 + r)**-n)).round
  end
end

app/models/mortgage_form.rb
# frozen_string_literal: true

# Represents a user's mortgage in terms of attributes for a form
class MortgageForm
  include ActiveModel::Model

  attr_accessor :amount
  attr_accessor :interest_rate_percentage
  attr_accessor :period_in_years
  attr_accessor :start_date
  attr_accessor :start_equity
  attr_accessor :time_zone

  validates :amount_milliunits, numericality: { greater_than: 0 }
  validates :interest_rate_percentage, numericality: { greater_than: 0 }
  validates :period_in_years,
            numericality: { greater_than: 0, only_integer: true }
  validates :start_date, presence: true
  validates :start_equity_milliunits,
            numericality: { greater_than_or_equal_to: 0 }
  validates :time_zone, presence: true

  def amount_currency_iso_code
    amount_milli_money.currency.iso_code
  end

  def amount_milliunits
    amount_milli_money.milliunits
  end

  def interest_rate
    BigDecimal(interest_rate_percentage) / BigDecimal(100)
  end

  def start_equity_milliunits
    start_equity_milli_money.milliunits
  end

  private

  def amount_milli_money
    @amount_milli_money ||= MilliMoney.parse(
      amount,
      Money.default_currency,
      assume_from_symbol: true
    )
  end

  def start_equity_milli_money
    @start_equity_milli_money ||= MilliMoney.parse(
      start_equity,
      amount_currency_iso_code
    )
  end
end

app/models/user.rb
# frozen_string_literal: true

# Represents an authenticated user of the application
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: %i[ynab]

  has_many :mortgages, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base controller class for the web application
class ApplicationController < ActionController::Base
  private

  def after_sign_in_path_for(_user)
    mortgages_path
  end
end

app/controllers/equity_trackers_controller.rb
# frozen_string_literal: true

# Responsible for managing mortgage equity trackers
class EquityTrackersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_mortgage, only: %i[new create destroy]
  before_action :initialize_form, only: %i[new create]

  def new
    prepare_form
  end

  def create
    if create_equity_tracker!
      render 'equity_trackers/create/success'
    else
      prepare_form
      render 'new'
    end
  end

  def destroy
    @mortgage.equity_tracker.destroy!
    redirect_to(mortgage_path(@mortgage), notice: 'Equity tracking removed.')
  end

  private

  def create_equity_tracker!
    EquityTrackers::Create.call(form: @equity_tracker_form, mortgage: @mortgage)
  end

  def find_accounts
    @accounts = ynab_api.accounts.get_accounts(
      @equity_tracker_form.budget_id
    ).data.accounts
  end

  def find_budgets
    @budgets = ynab_api.budgets.get_budgets.data.budgets
  end

  def find_data_for_step
    case @equity_tracker_form.step
    when 1 then find_budgets
    when 2, 3 then find_accounts
    end
  end

  def find_mortgage
    @mortgage = current_user.mortgages.find_by(id: params[:mortgage_id])
  end

  def initialize_form
    @equity_tracker_form = EquityTrackerForm.new(permitted_params)
  end

  def permitted_params
    params.fetch(:equity_tracker_form, {}).permit(
      :account_id,
      :budget_id,
      :payee_name,
      :step
    )
  end

  def prepare_form
    @equity_tracker_form.step -= 1 unless @equity_tracker_form.valid?
    find_data_for_step
  end

  def ynab_api
    YNAB::API.new(current_user.ynab_access_token)
  end
end

app/controllers/mortgages_controller.rb
# frozen_string_literal: true

# Responsible for managing mortgages
class MortgagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @mortgages = current_user.mortgages
  end

  def show
    @mortgage = current_user.mortgages.find_by(id: params[:id])
  end

  def new
    @mortgage_form = MortgageForm.new
  end

  def create
    @mortgage_form = MortgageForm.new(permitted_params)

    if create_mortgage!
      redirect_to(mortgages_path, notice: 'Mortgage added.')
    else
      render 'new'
    end
  end

  private

  def create_mortgage!
    Mortgages::Create.call(form: @mortgage_form, user: current_user)
  end

  def permitted_params
    params.require(:mortgage_form).permit(
      :amount,
      :interest_rate_percentage,
      :period_in_years,
      :start_date,
      :start_equity,
      :time_zone
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  # Responsible for handling the OAuth callback from YNAB
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def ynab
      user = Users::SynchronizedFromYNAB.call(
        auth_hash: request.env['omniauth.auth']
      )

      set_flash_message(:notice, :success, kind: 'YNAB')

      sign_in_and_redirect(user)
    end

    def failure
      redirect_to(root_path)
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Responsible for welcoming new visitors
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Responsible for providing helper methods to extract logic from the views
module ApplicationHelper
end

app/views/equity_trackers/create/success.html.erb
<%= render 'shared/navbar' %>
<section class="section">
  <div class="container">
    <h1 class="title">✅ You are good to go!</h1>
    <div class="content">
      <p>
        As new payments occur based on your amortization schedule, equity transactions will automatically appear in YNAB.
      </p>
      <p>
        Thank you for using YHAM!
      </p>
      <p>
        <%= link_to 'Click here to return to your YHAM mortgage list.', mortgages_path %>
      </p>
      <p>
        <%= link_to(
            'Click here to leave YHAM and go to YNAB.',
            'https://www.youneedabudget.com/'
          )
        %>
      </p>
    </div>
  </div>
</section>

app/views/equity_trackers/new.html.erb
<%= render 'shared/navbar' %>
<section class="section">
  <div class="container">
    <h1 class="title">Track your mortgage equity in YNAB</h1>
    <%= render 'shared/form_errors', form_object: @equity_tracker_form %>
    <%= render "equity_trackers/new/step_#{@equity_tracker_form.step}" %>
  </div>
</section>

app/views/equity_trackers/new/_step_1.html.erb
<%= form_with(
    method: :get,
    model: @equity_tracker_form,
    url: new_mortgage_equity_tracker_path(@mortgage)
  ) do |form|
%>
  <div class="columns">
    <div class="column">
      <div class="field">
        <%= form.label :budget_id, 'Budget', class: 'label' %>
        <div class="control is-expanded">
          <div class="select is-fullwidth">
            <%= form.collection_select :budget_id,
              @budgets,
              :id,
              :name,
              { prompt: true },
              { required: true }
            %>
          </div>
        </div>
      </div>
      <%= form.hidden_field :step, value: 2 %>
      <div class="notification">
        <p>Please create an account for equity in YNAB.</p>
        <p>
          <%= link_to(
              'Click here for instructions on adding an account.',
              'https://docs.youneedabudget.com/article/146-adding-an-account',
              target: '_blank'
            )
          %>
        </p>
        <p>
          The account should be unlinked, and the type will be <strong>Tracking: Asset</strong>.
        </p>
        <p>You will need to select that account on the next page.</p>
      </div>
      <div class="control">
        <%= form.submit 'Next step', class: 'button' %>
      </div>
    </div>
    <div class="column"><!-- I don't feel like writing CSS 😅 --></div>
  </div>
<% end %>

app/views/equity_trackers/new/_step_2.html.erb
<%= form_with(
    model: @equity_tracker_form,
    url: mortgage_equity_tracker_path(@mortgage)
  ) do |form|
%>
  <div class="columns">
    <div class="column">
      <div class="field">
        <%= form.label :account_id, 'Equity tracking account', class: 'label' %>
        <div class="control is-expanded">
          <div class="select is-fullwidth">
            <%= form.collection_select :account_id,
              @accounts,
              :id,
              :name,
              { prompt: true },
              { required: true }
            %>
          </div>
        </div>
      </div>
      <div class="field">
        <%= form.label :payee_name,
          'Payee name for equity transactions',
          class: 'label'
        %>
        <%= form.text_field :payee_name, class: 'input', required: true %>
      </div>
      <%= form.hidden_field :budget_id %>
      <%= form.hidden_field :step, value: 3 %>
      <div class="notification">
        <p>
          A transaction with your current equity will be created upon successful submission in the selected YNAB budget and account.
        </p>
      </div>
      <div class="control">
        <%= form.submit 'Submit', class: 'button' %>
      </div>
    </div>
    <div class="column"><!-- I don't feel like writing CSS 😅 --></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>YHAM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"
      rel="stylesheet"
    >
  </head>
  <body>
    <% if notice.present? %>
      <section>
        <div class="notification is-radiusless">
          <div class="container"><%= notice %></div>
        </div>
      </section>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/mortgages/index.html.erb
<%= render 'shared/navbar' %>
<section class="section">
  <div class="container">
    <h1 class="title">Mortgages</h1>
    <div class="field">
      <%= link_to "Add mortgage", new_mortgage_path, class: 'button' %>
    </div>
    <div class="tile is-ancestor">
      <% current_user.mortgages.each do |mortgage| %>
        <div class="tile is-parent">
          <div class="tile is-child box">
            <%= link_to(
                "#{mortgage.amount.format} Mortgage (#{mortgage.start_date})",
                mortgage_path(mortgage)
              )
            %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/mortgages/new.html.erb
<%= render 'shared/navbar' %>
<section class="section">
  <div class="container">
    <h1 class="title">Add your mortgage</h1>
    <%= render 'shared/form_errors', form_object: @mortgage_form %>
    <%= form_with model: @mortgage_form, url: mortgages_path do |form| %>
      <div class="columns">
        <div class="column">
          <div class="field">
            <%= form.label :amount, class: 'label' %>
            <div class="control">
              <%= form.text_field :amount, class: 'input', required: true %>
            </div>
          </div>
          <div class="field">
            <%= form.label :interest_rate_percentage,
              'Interest rate (%)',
              class: 'label'
            %>
            <div class="control">
              <%= form.number_field :interest_rate_percentage,
                class: 'input',
                min: 0,
                required: true,
                step: :any
              %>
            </div>
          </div>
          <div class="field">
            <%= form.label :period_in_years, 'Period (years)', class: 'label' %>
            <div class="control">
              <%= form.number_field :period_in_years,
                min: 1,
                class: 'input',
                required: true
              %>
            </div>
          </div>
          <div class="field">
            <%= form.label :start_date, class: 'label' %>
          </div>
          <div class="field has-addons">
            <div class="control">
              <%= form.date_field :start_date, class: 'input', required: true %>
            </div>
            <div class="control is-expanded">
              <div class="select is-fullwidth">
                <%= form.time_zone_select :time_zone,
                  ActiveSupport::TimeZone.us_zones,
                  { default: 'Eastern Time (US & Canada)' },
                  { 'aria-label': 'Time zone' }
                %>
              </div>
            </div>
          </div>
          <div class="field">
            <%= form.label :start_equity,
              'Down payment / equity before mortgage',
              class: 'label'
            %>
            <div class="control">
              <%= form.text_field :start_equity, class: 'input' %>
            </div>
          </div>
          <div class="control">
            <%= form.submit 'Submit', class: 'button' %>
          </div>
        </div>
        <div class="column"><!-- I don't feel like writing CSS 😅 --></div>
      </div>
    <% end %>
  </div>
</div>

app/views/mortgages/show.html.erb
<%= render 'shared/navbar' %>
<section class="section">
  <div class="container">
    <h1 class="title">Your Mortgage</h1>
    <div class="columns">
      <div class="column">
        <% if @mortgage.equity_tracker.present? %>
          <%= button_to 'Remove tracking in YNAB',
            mortgage_equity_tracker_path(@mortgage),
            class: 'button',
            method: :delete
          %>
        <% else %>
          <%= link_to 'Track this mortgage in YNAB',
            new_mortgage_equity_tracker_path(@mortgage),
            class: 'button'
          %>
        <% end %>
      </div>
      <div class="column">
        <p>Monthly payment: <%= @mortgage.monthly_payment.format %></p>
        <p>Total cost: <%= @mortgage.total_cost.format %></p>
      </div>
    </div>
    <table class='table is-bordered is-fullwidth is-hoverable'>
      <thead>
        <tr>
          <th class="has-text-centered" colspan="6">Amortization Schedule</th>
        </tr>
        <tr>
          <th>Payment #</th>
          <th>Date</th>
          <th>Interest</th>
          <th>Principal</th>
          <th>Balance</th>
          <th>Equity</th>
        </tr>
      </thead>
      <tbody>
        <% @mortgage.amortization_schedule.each do |period| %>
          <tr>
            <td><%= period.number %></td>
            <td><%= period.date %></td>
            <td><%= period.interest.format %></td>
            <td><%= period.principal.format %></td>
            <td><%= period.balance.format %></td>
            <td><%= period.equity.format %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/shared/_form_errors.html.erb
<% if form_object.errors.any? %>
  <div class="content notification">
    <h2 class="subtitle">
      <%= pluralize(form_object.errors.count, 'error') %> prevented progress:
    </h2>
    <ul>
      <% form_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-link" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to(
          '🏠 YHAM',
          mortgages_path,
          class: 'navbar-item has-text-weight-bold is-size-3'
        )
      %>
      <div class="navbar-item">
        <%= button_to(
            'Sign out',
            sign_out_path,
            class: 'button',
            method: :delete
          )
        %>
      </div>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<section class="hero is-link">
  <div class="hero-body">
    <div class="container">
      <h1 class="has-text-centered title">🏠 YHAM - You Have A Mortgage</h1>
      <hr role="presentation">
      <p class="has-text-weight-semibold subtitle">
        YHAM is a web application to help people see the true value of their mortgage.
      </p>
      <p class="has-text-weight-semibold subtitle">
        It provides an unofficial <a href="https://www.youneedabudget.com/">YNAB</a> plugin that automatically tracks your home equity in YNAB as you pay off your mortgage.
      </p>
      <div class="level">
        <div class="level-item">
          <img
            alt="Demonstration of YHAM tracking equity in YNAB"
            src="yham-demonstration.png"
          >
        </div>
      </div>
      <div class="field is-grouped is-grouped-centered">
        <div class="control">
            <%= link_to(
                'Sign in with YNAB',
                user_ynab_omniauth_authorize_path,
                class: 'button'
              )
            %>
        </div class="control">
        <div>
            <%= link_to(
                'View source code',
                'https://gitlab.com/grantbdev/yham',
                class: 'button'
              )
            %>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="hero">
  <div class="hero-body">
    <div class="container content">
      <h2 class="subtitle">🔒 Privacy Policy</h2>
      <ul>
        <li>
          YHAM follows the guidelines for integrating with your YNAB account using the YNAB API.
        </li>
        <li>
          All data between YHAM and YNAB is encrypted when it is exchanged.
        </li>
        <li>
          YHAM only stores explictly provided information and only as needed to provide the service.
        </li>
        <li>
          Any required data is stored in a secure and private database provided by Heroku.
        </li>
        <li>
          Your information will never be shared with any third-party.
        </li>
      </ul>
    </div>
  </div>
</section>